# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    (1..1).each do |i|
        config.vm.define "controller#{i}" do |controller|
            controller.vm.box = "ubuntu/trusty64"
            controller.vm.hostname = "controller#{i}"
            
            controller.vm.provider "virtualbox" do |vb|
                vb.name = "controller#{i}"
                vb.memory = "2048"
                vb.cpus = "2"
                file_to_disk = "./controller#{i}_disk.vdi"
        
                vb.customize ['createhd', '--filename', file_to_disk, '--size', 50 * 1024]
                vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

                vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet0"]
                vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet1"]

            end

            controller.vm.provision "shell", path: "./controller-lvm.sh"

        end
    
    end

 
    (1..3).each do |i|
        config.vm.define "compute#{i}" do |compute|
            compute.vm.box = "ubuntu/trusty64"
            compute.vm.hostname = "compute#{i}"
            
            compute.vm.provider "virtualbox" do |vb|
                vb.name = "compute#{i}"
                vb.memory = "2048"
                vb.cpus = "2"
                file_to_disk = "./compute#{i}_disk.vdi"
        
                vb.customize ['createhd', '--filename', file_to_disk, '--size', 50 * 1024]
                vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

                vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet0"]
                vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet1"]
            end
        
            compute.vm.provision "shell", path: "./compute-lvm.sh"
 
        end
    end
end
